// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK1RuQgsneebIXp3kpT1cz4IRq95gjuQ',
    appId: '1:763157255692:web:6558524ac554f6f8b20029',
    messagingSenderId: '763157255692',
    projectId: 'fire-flutter-d736e',
    authDomain: 'fire-flutter-d736e.firebaseapp.com',
    storageBucket: 'fire-flutter-d736e.appspot.com',
    measurementId: 'G-5V0PH1FPHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXaOvGlmkgH1sB0eiRvE2tbbEuAqjyvqA',
    appId: '1:763157255692:android:c84b2fbaca9972bbb20029',
    messagingSenderId: '763157255692',
    projectId: 'fire-flutter-d736e',
    storageBucket: 'fire-flutter-d736e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYptq6tVO0dqPydjtLCVX5ZVFzjPJyYY',
    appId: '1:763157255692:ios:d6821c01a9b95766b20029',
    messagingSenderId: '763157255692',
    projectId: 'fire-flutter-d736e',
    storageBucket: 'fire-flutter-d736e.appspot.com',
    iosClientId: '763157255692-2nlbij2ks47lskvg58p6rqpbqrsu9m36.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYptq6tVO0dqPydjtLCVX5ZVFzjPJyYY',
    appId: '1:763157255692:ios:d6821c01a9b95766b20029',
    messagingSenderId: '763157255692',
    projectId: 'fire-flutter-d736e',
    storageBucket: 'fire-flutter-d736e.appspot.com',
    iosClientId: '763157255692-2nlbij2ks47lskvg58p6rqpbqrsu9m36.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
